update StringTracker with new fields from python library
whylabs/whylogs-java pull request #34
Opened 2021-07-20 16:58 UTC by cswarth

Port StringTracker from whylogs-python

2021-07-20 21:01 UTC, andyndang requested changes

2021-07-20 21:01 UTC, andyndang commented on core/src/main/java/com/whylogs/core/statistics/datatypes/CharPosTracker.java
> +    AtomicInteger i = new AtomicInteger();
why are we using `AtomicInteger` here? I don't see any multithreading logic. You can just use a mutable `i` and run `update(i++, cp)`

2021-07-20 21:01 UTC, andyndang commented on core/src/main/java/com/whylogs/core/statistics/datatypes/CharPosTracker.java
> +    value.codePoints().forEach(cp -> update(i.getAndIncrement(), cp));
I see what you're doing here. It's clearer to just do: `value.codePoints().toArray()` and then `for (int i = 0; i < cp.len; i++) update(i, cp[i])`

2021-07-20 21:01 UTC, andyndang commented on core/src/main/java/com/whylogs/core/statistics/datatypes/CharPosTracker.java
> +  public void update(String value, String charString) {
Can we add some public doc around these methods

2021-07-20 23:34 UTC, cswarth commented on core/src/main/java/com/whylogs/core/statistics/datatypes/CharPosTracker.java
> +    AtomicInteger i = new AtomicInteger();
I tried that way first, but all variables referenced from lambda must be effectively final.
`Variable used in lambda expression should be final or effectively final`
Converting to Atomic is the suggested fix, but I can also turn this into an old-style for-loop.

2021-07-21 22:03 UTC, lalmei approved these changes
LGTM

2021-07-21 22:31 UTC, andyndang approved these changes
LGTM

2021-07-21 22:53 UTC, merged